### ISSUE TITLE
ModelicaCompliance.Arrays.Functions.Size.ArrayDimSizeIncorrectArgument3 is incorrect

### ISSUE THREAD

**Issue by miscco** [modelica/Modelica-Compliance#24]
The test 

> ModelicaCompliance.Arrays.Functions.Size.ArrayDimSizeIncorrectArgument3

appears to be incorrect. In section "10.3.1 Array Dimension and Size Functions" Table 10-3 it is stated, that 
```
ndims(A)    Returns the number of dimensions k of array expression A, with k >= 0.
size(A)     Returns a vector of length ndims(A) containing the dimension sizes of A.
```

Therefore, ``size(A)`` of an scalar should return an empty vector (with length ndims(A)==0), but would still be a valid statement.

**Comment by FrenkelJ** [comment]
I agree with @miscco because the Spec (3.4) state for size(A):
> Returns a vector of length ndims(A) containing the dimension sizes of A.

There are no restrictions for A.

In addition the Spec (3.4) states for ndims(A):
> Returns the number of dimensions k of expression A, with k >= 0.

There are also no restrictions for A. In @miscco  comment was the wrong restriction "array expression A" mentioned.

**Comment by HansOlsson** [comment]
I also agree that they should be legal. 

Practically speaking since Modelica is strongly typed I don't see a major use-case in the language for ndims (for any argument) or size of a scalar.

I can see a use of ndims in discussing Modelica-semantics which is consistent with ndims being used in several places in the specification, but not in MSL. The use in the specification also indicates that ndims and size should be applicable to scalars, since it is most general and already used e.g.:

> `[A; B; C; ...] = cat(1, promote(A,n), promote(B,n), promote(C,n), ...)` where `n = max(2, ndims(A), ndims(B), ndims(C), ....). ` and 

> The constructor function `array(A,B,C,...)` constructs an array from its arguments according to the following rules:
>  Size matching: All arguments must have the same sizes, i.e., `size(A)=size(B)=size(C)=...`
